baseURL = 'https://blog.shelchin.com/'
languageCode = 'en-us'
title = 'Shelchin'
theme = 'anatole'
enableRobotsTXT =true

[params]
title = "I'm Shelchin"
author = "Shelchin"
description = "Be sincere; be brief; be seated."
profilePicture = "images/profile.jpg"
contentratio = 0.8
readMore = true
rssFullContent = true
mainSections = []
disableComments =false
postSectionName ="posts"
customCss = ["css/custom.css", "css/styles.css"]
 
[params.umami]
serverURL = "us.umami.is"
id = "52fe77a1-0dfb-48af-89f4-eef4310b4732"
trackerScriptName = "script.js"

[params.giscus]
repo = "atshelchin/shelchin-blog"
repoID = "R_kgDOK34WPw"
category = "General"
categoryID = "DIC_kwDOK34WP84Cbn-U"
mapping = "title"
reactionsEnabled = "1"
inputPosition = "bottom"
loading = "lazy"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/atshelchin"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/atshelchin"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:hi@shelchin.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Diary"
  weight = 300
  identifier = "diary" 
  url = "/diary/" 


  [[menu.main]]
  name = "Notes"
  weight = 400
  identifier = "notes" 
  url = "/notes/" 


  [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"
